"""add ydata profile artifact uri

Revision ID: ba0e57fedf38
Revises: 569c9af54b7d
Create Date: 2026-09-03 00:23:34.044152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0e57fedf38'
down_revision: Union[str, Sequence[str], None] = '569c9af54b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_profiles', sa.Column('ydata_profile_uri', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_profiles', 'ydata_profile_uri')
    # ### end Alembic commands ###
